import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../services/supabase'
import { assetPreviewUrl, uploadImmutablePng } from '../../services/masterV1Assets'

const CLIENTE_ID = 'cd287e6e-f273-4d0f-a72d-2a8c391e40e9'
const DEFAULT_MAP = { news_image: '', headline: '', tag: '', visual_title: 'tag-png', sponsor_1: 'patrocinador-1', sponsor_2: 'patrocinador-2' }
const emptyTitle = { nome: '', slug: '', formatos: ['feed', 'reels'], ordem: 0, ativo: true }

function Slot({ label, asset, onChange }) {
  const preview = asset ? assetPreviewUrl(supabase, asset) : null
  return <div style={{ border: '1px solid #e2e8f0', borderRadius: 10, padding: 12, display: 'grid', gap: 8 }}><strong>{label}</strong>{preview && <img src={preview} alt={label} style={{ maxHeight: 52, maxWidth: 180, objectFit: 'contain' }} />}<input type="file" accept="image/png" onChange={e => onChange(e.target.files?.[0] || null)} />{asset && <button className="ap-btn-sm" onClick={() => onChange(null)}>Limpar slot</button>}</div>
}

export default function AutoPublisherMasterV1Settings() {
  const [tab, setTab] = useState('titles'); const [titles, setTitles] = useState([]); const [templates, setTemplates] = useState([]); const [profiles, setProfiles] = useState([]); const [configs, setConfigs] = useState([]); const [control, setControl] = useState({ kill_switch: false }); const [title, setTitle] = useState(emptyTitle); const [titleFile, setTitleFile] = useState(null); const [selectedTemplate, setSelectedTemplate] = useState(''); const [profileAssets, setProfileAssets] = useState({ sponsor_1: undefined, sponsor_2: undefined }); const [format, setFormat] = useState('feed'); const [masterUuid, setMasterUuid] = useState(''); const [templateSet, setTemplateSet] = useState(''); const [enabled, setEnabled] = useState(false); const [layerMap, setLayerMap] = useState(DEFAULT_MAP); const [message, setMessage] = useState('');
  const notice = text => setMessage(text)
  async function load() { const [a,b,c,d,e] = await Promise.all([supabase.schema('ap').from('visual_titles').select('*').eq('cliente_id', CLIENTE_ID).order('ordem'),supabase.schema('ap').from('templates').select('id,nome,tipo,template_set,ordem,placid_template_uuid,ativo,uso_total').eq('empresa_id', CLIENTE_ID).order('ordem'),supabase.schema('ap').from('template_render_profiles').select('*'),supabase.schema('ap').from('master_render_configs').select('*').eq('cliente_id', CLIENTE_ID),supabase.schema('ap').from('master_render_controls').select('*').eq('cliente_id', CLIENTE_ID).maybeSingle()]); setTitles(a.data||[]);setTemplates(b.data||[]);setProfiles(c.data||[]);setConfigs(d.data||[]);setControl(e.data||{kill_switch:false}) }
  useEffect(() => { load().catch(error => notice(error.message)) }, [])
  const activeTitle = titles.find(item => item.ativo)
  async function saveTitle() { try { if (!title.nome || !title.slug || !titleFile) throw new Error('Nome, slug e PNG são obrigatórios.'); const asset = await uploadImmutablePng({ supabase, file:titleFile, clienteId:CLIENTE_ID, kind:'visual-titles', slug:title.slug }); const { error } = await supabase.schema('ap').from('visual_titles').insert({ ...title, cliente_id:CLIENTE_ID, asset_bucket:asset.bucket, asset_path:asset.path, asset_version:asset.version, sha256:asset.sha256 }); if(error) throw error; setTitle(emptyTitle);setTitleFile(null);notice('Título visual salvo.');load() } catch(error) { notice(error.message) } }
  async function saveProfile() { try { if(!selectedTemplate) throw new Error('Selecione uma linha de template.'); const current = profiles.find(p=>p.template_id===selectedTemplate); const slots={ ...(current?.other_slots||{}) }; for(const slot of ['sponsor_1','sponsor_2']) { const input=profileAssets[slot]; if(input===undefined) continue; if(input===null) delete slots[slot]; else slots[slot]=await uploadImmutablePng({supabase,file:input,clienteId:CLIENTE_ID,kind:'sponsors',slug:`${selectedTemplate}-${slot}`}); } const payload={ template_id:selectedTemplate, profile_version:new Date().toISOString(), other_slots:slots, ativo:true }; const query=current?supabase.schema('ap').from('template_render_profiles').update(payload).eq('id',current.id):supabase.schema('ap').from('template_render_profiles').insert(payload);const {error}=await query;if(error)throw error;setProfileAssets({sponsor_1:undefined,sponsor_2:undefined});notice('Perfil salvo.');load() } catch(error){notice(error.message)} }
  async function saveMaster() { try { const duplicates=Object.entries(layerMap).filter(([,value])=>value).map(([,value])=>value); if(new Set(duplicates).size!==duplicates.length) throw new Error('Layer map possui nomes duplicados.'); if(enabled && (!masterUuid || !layerMap.visual_title || !activeTitle)) throw new Error('Ativação exige UUID, layer visual_title e título visual ativo.'); const current=configs.find(c=>c.content_type===format && (c.template_set||'')===templateSet);const payload={cliente_id:CLIENTE_ID,content_type:format,template_set:templateSet||null,master_template_uuid:masterUuid||null,enabled,layer_map:layerMap};const {error}=current?await supabase.schema('ap').from('master_render_configs').update(payload).eq('id',current.id):await supabase.schema('ap').from('master_render_configs').insert(payload);if(error)throw error;notice('Configuração master salva.');load()}catch(error){notice(error.message)} }
  async function saveKill(){const {error}=await supabase.schema('ap').from('master_render_controls').upsert({cliente_id:CLIENTE_ID,kill_switch:control.kill_switch});if(error)notice(error.message);else notice('Kill switch salvo.');}
  const previewProfile=profiles.find(p=>p.template_id===selectedTemplate); const previewSlots=useMemo(()=>previewProfile?.other_slots||{},[previewProfile]); const payload=useMemo(()=>({template_uuid:enabled&&masterUuid?masterUuid:(templates.find(t=>t.id===selectedTemplate)?.placid_template_uuid||'<UUID legado>'),layers:Object.fromEntries([['visual_title',activeTitle&&layerMap.visual_title?[layerMap.visual_title,{image:assetPreviewUrl(supabase,{bucket:activeTitle.asset_bucket,path:activeTitle.asset_path})}]:null],...['sponsor_1','sponsor_2'].map(slot=>previewSlots[slot]&&layerMap[slot]?[layerMap[slot],{image:assetPreviewUrl(supabase,previewSlots[slot])}]:null)].filter(Boolean))}),[enabled,masterUuid,templates,selectedTemplate,activeTitle,layerMap,previewSlots]);
  return <div className="ap-settings"><div className="ap-form-section"><h2>Master v1</h2><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}>{[['titles','Títulos visuais'],['profiles','Patrocinadores'],['masters','Templates master'],['diagnostic','Diagnóstico']].map(([key,label])=><button key={key} className={tab===key?'ap-btn-add':'ap-btn-outline'} onClick={()=>setTab(key)}>{label}</button>)}</div>{message&&<p style={{color:'#475569'}}>{message}</p>}
  {tab==='titles'&&<><div className="ap-form-row"><input className="ap-input" placeholder="Nome" value={title.nome} onChange={e=>setTitle({...title,nome:e.target.value})}/><input className="ap-input" placeholder="slug" value={title.slug} onChange={e=>setTitle({...title,slug:e.target.value})}/><input className="ap-input" type="number" value={title.ordem} onChange={e=>setTitle({...title,ordem:Number(e.target.value)})}/><label><input type="checkbox" checked={title.formatos.includes('feed')} onChange={e=>setTitle({...title,formatos:e.target.checked?[...new Set([...title.formatos,'feed'])]:title.formatos.filter(x=>x!=='feed')})}/> Feed</label><label><input type="checkbox" checked={title.formatos.includes('reels')} onChange={e=>setTitle({...title,formatos:e.target.checked?[...new Set([...title.formatos,'reels'])]:title.formatos.filter(x=>x!=='reels')})}/> Reels</label><input type="file" accept="image/png" onChange={e=>setTitleFile(e.target.files?.[0]||null)}/><button className="ap-btn-add" onClick={saveTitle}>Salvar PNG</button></div><table className="ap-table"><thead><tr><th>Preview</th><th>Nome</th><th>Formatos</th><th>Ordem</th><th>Ativo</th></tr></thead><tbody>{titles.map(item=><tr key={item.id}><td>{<img src={assetPreviewUrl(supabase,{bucket:item.asset_bucket,path:item.asset_path})} alt="" style={{height:30,maxWidth:90,objectFit:'contain'}}/>}</td><td>{item.nome}</td><td>{item.formatos.join(', ')}</td><td>{item.ordem}</td><td><button className={`ap-toggle ${item.ativo?'on':'off'}`} onClick={async()=>{await supabase.schema('ap').from('visual_titles').update({ativo:!item.ativo}).eq('id',item.id);load()}}>{item.ativo?'Ativo':'Arquivado'}</button></td></tr>)}</tbody></table></>}
  {tab==='profiles'&&<><select className="ap-select" value={selectedTemplate} onChange={e=>{setSelectedTemplate(e.target.value);setProfileAssets({sponsor_1:undefined,sponsor_2:undefined})}}><option value="">Selecione template rotacionado</option>{templates.map(t=><option key={t.id} value={t.id}>{t.nome} · {t.tipo} · {t.template_set} · #{t.ordem}</option>)}</select>{selectedTemplate&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginTop:12}}><Slot label="Patrocinador 1" asset={previewSlots.sponsor_1} onChange={file=>setProfileAssets({...profileAssets,sponsor_1:file})}/><Slot label="Patrocinador 2" asset={previewSlots.sponsor_2} onChange={file=>setProfileAssets({...profileAssets,sponsor_2:file})}/></div><button className="ap-btn-add" style={{marginTop:12}} onClick={saveProfile}>Salvar perfil</button></>}</>}
  {tab==='masters'&&<><div className="ap-form-row"><select className="ap-select" value={format} onChange={e=>setFormat(e.target.value)}><option value="feed">Feed</option><option value="reels">Reels</option></select><input className="ap-input" placeholder="UUID master (opcional)" value={masterUuid} onChange={e=>setMasterUuid(e.target.value.trim())}/><input className="ap-input" placeholder="template_set opcional" value={templateSet} onChange={e=>setTemplateSet(e.target.value)}/><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enabled</label><button className="ap-btn-add" onClick={saveMaster}>Salvar</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:8}}>{Object.keys(DEFAULT_MAP).map(key=><label key={key}>{key}<input className="ap-input" value={layerMap[key]||''} placeholder="Ausente" onChange={e=>setLayerMap({...layerMap,[key]:e.target.value.trim()})}/></label>)}</div><label style={{display:'block',marginTop:16}}><input type="checkbox" checked={control.kill_switch} onChange={e=>setControl({...control,kill_switch:e.target.checked})}/> Kill switch global</label><button className="ap-btn-outline" onClick={saveKill}>Salvar kill switch</button></>}
  {tab==='diagnostic'&&<><p>Selecione um template na aba Patrocinadores para simular os quatro cenários de slots sem chamar Placid.</p><pre style={{background:'#0f172a',color:'#e2e8f0',padding:16,borderRadius:10,overflow:'auto'}}>{JSON.stringify({format,legacy_uuid:templates.find(t=>t.id===selectedTemplate)?.placid_template_uuid||null,master_uuid:masterUuid||null,contract:enabled&&masterUuid?'master_v1':'legacy',payload},null,2)}</pre></>}
  </div></div>
}